### ISSUE TITLE
StreamRadio crashes on launch when built with GCC 8.3

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/Haiku-Radio#8]
hrev53233 x86_64
Built Haiku-Radio from source. The app crashes on launch. The version I already had installed does not. Debugger report below:
```
Debug information for team /boot/home/HaikuArchives/Haiku-Radio/dist/StreamRadio (3560):
CPU(s): 8x Intel Core™ i7-3770
Memory: 15.88 GiB total, 797.00 MiB used
Haiku revision: hrev53233 Jul  5 2019 17:08:51 (x86_64)

Active Threads:
	thread 3563: team 3560 debug task 
	thread 3560: StreamRadio (main)
		state: Exception (Segment violation)

		Frame		IP			Function Name
		-----------------------------------------------
		0x7fd6313927a0	0x1f99b7fc760	BEntry::GetStat(stat*) const@@LIBBE_1_ALPHA1 + 0 
			Disassembly:
				BEntry::GetStat(stat*) const@@LIBBE_1_ALPHA1:
				0x000001f99b7fc760:           8b4728  mov 0x28(%rdi), %eax <--

			Frame memory:
				[0x7fd631392798]  ........   b0 c7 7f 9b f9 01 00 00
		0x7fd631392850	0x1f99b7fc7ab	BEntry::_GetStat(stat_beos*) const + 0x1b 
		0x7fd631392a30	0xb392f68177	_Unwind_ForcedUnwind_Phase2(_Unwind_Exception*, _Unwind_Context*, long unsigned int*) + 0x57 (/sources/gcc-8.3.0/libgcc/unwind.inc:-1)
			Variables:
			exc: 0x1f99bae56b0 {
				exception_class: 2171567323184
				exception_cleanup: 0x1f99b7fb860
				private_1: 2171567327120
				private_2: 2171567327072
			}
			context: 0x7fd631392b30 {
				reg: Unavailable
				cfa: 0x7fd631392c70
				ra: 0x19704367146
				lsda: 0x197043788fa
				flags: 4611686018427387904
				version: 0
				args_size: 0
				by_value: 
			}
			frames_p: 0x7fd631392a38 {
				*frames_p: 140557925559088
			}
			stop: 0x1f99b7fc790
			stop_argument: 0x1f99b7fc760 {
				*stop_argument: Unavailable
			}
			code: _URC_NO_REASON
			frames: 1
			fs {
				pc: 0x1970436712e
				personality: 0xc625853910
				data_align: -8
				code_align: 1
				retaddr_column: 16
				fde_encoding: 27
				lsda_encoding: 27
				saw_z: 1
				signal_frame: 0
				eh_ptr: 0
			}
			action: 652

		0x7fd631392c60	0xb392f68990	_Unwind_Resume + 0x180 
		0x7fd631392d10	0x19704367146	_ZN12StationsList4SaveEv.cold.8 + 0 
		0x7fd631392e60	0x1970436b05a	RadioSettings::Load() + 0xca 
		0x7fd631392e90	0x1970436b0bf	RadioSettings::RadioSettings() + 0x3f 
		0x7fd631392eb0	0x1970436a78b	RadioApp::RadioApp() + 0x2b 
		0x7fd631392ed0	0x19704367e71	main + 0x21 
		0x7fd631392f00	0x197043681c9	_start + 0x39 
		0x7fd631392f30	0x208401fc573	runtime_loader + 0x103 
		00000000	0x7fce18ea6260	commpage_thread_exit + 0 

```

**Comment by Vidrep** [comment]
@jsteinaker

**Comment by jsteinaker** [comment]
It's not crashing here. I've uploaded a new HaikuPorts recipe a few hours ago, which doesn't use the patchset anymore, since the changes that were there are already merged on the tree. It's not merged yet but you should be able to get it anyway. Starting with that recipe only I can sucessfully build StreamRadio, downloading the sources from GitHub, and it doesn't crash. I was thinking that maybe the patch (if you're using it) is breaking something...

Also, it seems the crash is coming from the Load method in Radio Settings class. I haven't changed anything there. Save() method now calls Rewind(), so it actually deletes a Station when asked, but that method shouldn't be called on startup anyway. Did you try deleting your "Stations" folder?

Thanks for reporting!

**Comment by Vidrep** [comment]
Did you test on 64 bit? I also built from the new recipe, and it also crashes (same as above). I tried deleting the "stations" folder too. Same.
Previously installed version works OK.

**Comment by jsteinaker** [comment]
Yes, I'm on x64. It would be great if more people could try building the new version to see what happens.

**Comment by humdingerb** [comment]
c983b6e3ed5c5ef9b3f53ef8a6204d1cd5e0cdd8  works on 32bit (hrev53209).

**Comment by diversys** [comment]
c983b6e crashes on 64bit (hrev53233)

**Comment by jsteinaker** [comment]
Just downloaded last 64bit nightly (hrev53237) to start the build absolutely from scratch. Works fine here.

Maybe a stupid idea but... how much memory do you guys have? Real hardware or VM? The main difference between your setup and mine that I can think of it's this one, I'm on a VM with only 2-3gb of RAM...

**Comment by waddlesplash** [comment]
Try using the guarded heap, it's possible some slight difference is triggering memory corruption which the guarded heap should catch.

**Comment by jsteinaker** [comment]
Do you mean this?
https://www.haiku-os.org/blog/mmlr/2010-02-08_using_malloc_debug_find_memory_related_bugs/

Also, what about the while condition check line in the Load() method in RadioSettings.cpp? I'm taking about operator precedence, I guess that might be wrong but I can't check now

**Comment by Vidrep** [comment]
Built on real hardware. x86_64 Core i7-3770, 16GB memory

**Comment by waddlesplash** [comment]
Yes, you'll want the guarded heap though, so in addition to the LD_PRELOAD, add `MALLOC_DEBUG=g` also.

**Comment by Vidrep** [comment]
Running the following: LD_PRELOAD=libroot_debug.so MALLOC_DEBUG=g StreamRadio

``
Debug information for team /boot/system/apps/StreamRadio (920):
CPU(s): 8x Intel Core™ i7-3770
Memory: 15.88 GiB total, 624.45 MiB used
Haiku revision: hrev53233 Jul  5 2019 17:08:51 (x86_64)

Active Threads:
	thread 923: team 920 debug task 
	thread 920: StreamRadio (main)
		state: Call (abort() called)

		Frame		IP			Function Name
		-----------------------------------------------
		00000000	0x2095f3a9e7f	_kern_debugger + 0x7 
			Disassembly:
				_kern_debugger:
				0x000002095f3a9e78:   48c7c0e1000000  mov $0xe1, %rax
				0x000002095f3a9e7f:             0f05  syscall  <--

		0x7feee7ffa770	0x2095f3a1cc3	abort + 0x4a 
		0x7feee7ffa9b0	0x1326f918773	__absvdi2(DItype) + 0x73 (/sources/gcc-8.3.0/libgcc/libgcc2.c:-1)
		0x7feee7ffaa50	0x1d8ba1f4146	_ZN12StationsList4SaveEv.cold.8 + 0 
		0x7feee7ffaba0	0x1d8ba1f805a	RadioSettings::Load() + 0xca 
		0x7feee7ffabd0	0x1d8ba1f80bf	RadioSettings::RadioSettings() + 0x3f 
		0x7feee7ffabf0	0x1d8ba1f778b	RadioApp::RadioApp() + 0x2b 
		0x7feee7ffac10	0x1d8ba1f4e71	main + 0x21 
		0x7feee7ffac40	0x1d8ba1f51c9	_start + 0x39 
		0x7feee7ffac70	0x99501c3573	runtime_loader + 0x103 
		00000000	0x7fff3d81d260	commpage_thread_exit + 0 

		Registers:
			  rip:	0x000002095f3a9e81
			  rsp:	0x00007feee7ffa738
			  rbp:	0x00007feee7ffa760
			  rax:	0x00000000000000e1
			  rbx:	0x000002095f6d64a0
			  rcx:	0x000002095f3a9e81
			  rdx:	0x00007feee7ffa23e
			  rsi:	0x0000000000000001
			  rdi:	0x000002095f4accf8
			   r8:	0x00007feee7ff7c05
			   r9:	0x00000000fffffff2
			  r10:	0x000002095f4accf8
			  r11:	0x0000000000003206
			  r12:	0x00007feee7ffa780
			  r13:	0x00007feee7ffa870
			  r14:	0x0000000000519fa0
			  r15:	0x0000000002f91e00
			   cs:	0x002b
			   ds:	0x0000
			   es:	0x0000
			   fs:	0x0000
			   gs:	0x0000
			   ss:	0x0023
			  st0:	0
			  st1:	0
			  st2:	0
			  st3:	0
			  st4:	0
			  st5:	0
			  st6:	0
			  st7:	0
			  mm0:	{0, 0, 0, 0}
			  mm1:	{0, 0, 0, 0}
			  mm2:	{0, 0, 0, 0}
			  mm3:	{0, 0, 0, 0}
			  mm4:	{0, 0, 0, 0}
			  mm5:	{0, 0, 0, 0}
			  mm6:	{0, 0, 0, 0}
			  mm7:	{0, 0, 0, 0}
			 xmm0:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm1:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm2:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm3:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm4:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm5:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm6:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm7:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm8:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm9:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm10:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm11:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm12:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm13:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm14:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm15:	{0, 0, 0, 0, 0, 0, 0, 0}

Loaded Images:
	ID		Text Base	Text End	Data Base	Data End	Type	Name
	--------------------------------------------------------------------------------
	3249	0x1c033b3000	0x1c033f4000	0x1c035f3000	0x1c035fc000	lib    	/boot/system/lib/libnetwork.so
	3248	0x2e41511000	0x2e4160c000	0x2e4180c000	0x2e4180f000	lib    	/boot/system/lib/libtextencoding.so
	3250	0x5855a33000	0x5855c35000	0x5855e34000	0x5855e5d000	lib    	/boot/system/lib/libcrypto.so.1.0.0
	3237	0x88e37a5000	0x88e38fb000	0x88e3afb000	0x88e3b08000	lib    	/boot/system/lib/libxml2.so.2.9.9
	3234	0x9214033000	0x9214048000	0x9214247000	0x9214249000	lib    	/boot/system/lib/libtranslation.so
	3229	0x99501af000	0x99501d0000	0x99503cf000	0x99503d2000	lib    	/boot/system/runtime_loader
	3251	0xc112025000	0xc11208f000	0xc11228e000	0xc112299000	lib    	/boot/system/lib/libssl.so.1.0.0
	3235	0xcfea1cd000	0xcfea233000	0xcfea433000	0xcfea438000	lib    	/boot/system/lib/libbnetapi.so
	3247	0x10fad6db000	0x10fad7ae000	0x10fad9ae000	0x10fad9af000	lib    	/boot/system/lib/libzstd.so.1.3.8
	3245	0x1289d86b000	0x1289da03000	0x1289dc02000	0x1289dc17000	lib    	/boot/system/lib/libicuuc.so.57.1
	3238	0x1326f916000	0x1326f92c000	0x1326fb2b000	0x1326fb2c000	lib    	/boot/system/lib/libgcc_s.so.1
	3242	0x13cff865000	0x13cff8ba000	0x13cffaba000	0x13cffabd000	lib    	/boot/system/lib/libicule.so.57.1
	3232	0x150d865d000	0x150d87bf000	0x150d89bf000	0x150d89d3000	lib    	/boot/system/lib/libstdc++.so.6.0.25
	3252	0x195912e6000	0x195912ed000	0x195914ec000	0x195914ed000	lib    	/boot/system/lib/libbsd.so
	3241	0x1bb20207000	0x1bb20213000	0x1bb20412000	0x1bb20414000	lib    	/boot/system/lib/libicuio.so.57.1
	3236	0x1caab076000	0x1caab12a000	0x1caab32a000	0x1caab336000	lib    	/boot/system/lib/libmedia.so
	3243	0x1d408c1c000	0x1d408c27000	0x1d408e27000	0x1d408e28000	lib    	/boot/system/lib/libiculx.so.57.1
	3230	0x1d8ba1da000	0x1d8ba207000	0x1d8ba407000	0x1d8ba40a000	app    	/boot/system/apps/StreamRadio
	3246	0x1e22b225000	0x1e22b241000	0x1e22b440000	0x1e22b441000	lib    	/boot/system/lib/libz.so.1.2.11
	3244	0x1e25ffe4000	0x1e260013000	0x1e260213000	0x1e260247000	lib    	/boot/system/lib/libicutu.so.57.1
	3240	0x1e29bd21000	0x1e29bf9e000	0x1e29c19d000	0x1e29c1b2000	lib    	/boot/system/lib/libicui18n.so.57.1
	3233	0x1fa10dba000	0x1fa110d2000	0x1fa112d2000	0x1fa11300000	lib    	/boot/system/lib/libbe.so
	3239	0x2081082d000	0x208120ab000	0x208122aa000	0x208122ab000	lib    	/boot/system/lib/libicudata.so.57.1
	3231	0x2095f368000	0x2095f4c9000	0x2095f6c9000	0x2095f71b000	lib    	/boot/system/lib/libroot_debug.so
	3228	0x7fff3d81d000	0x7fff3d825000	0x00000000	0x00000000	system 	commpage

Areas:
	ID		Base		End			Size (KiB)	Protection	Locking			Name
	--------------------------------------------------------------------------------
	9671	0x0016a000	0x0036a000	      2048	rw-        	full          	guarded_heap_area
	9670	0x00373000	0x00573000	      2048	rw-        	full          	guarded_heap_area
	9688	0x005ac000	0x007ac000	      2048	rw-        	full          	guarded_heap_area
	9681	0x007db000	0x009db000	      2048	rw-        	full          	guarded_heap_area
	9702	0x00bd4000	0x00dd4000	      2048	rw-        	full          	guarded_heap_area
	9693	0x00f00000	0x01100000	      2048	rw-        	full          	guarded_heap_area
	9703	0x01207000	0x01407000	      2048	rw-        	full          	guarded_heap_area
	9704	0x0143b000	0x0163b000	      2048	rw-        	full          	guarded_heap_area
	9667	0x01672000	0x01872000	      2048	rw-        	full          	guarded_heap_area
	9708	0x018aa000	0x01aaa000	      2048	rw-        	full          	guarded_heap_area
	9707	0x01b21000	0x01d21000	      2048	rw-        	full          	guarded_heap_area
	9709	0x01d7f000	0x01f7f000	      2048	rw-        	full          	guarded_heap_area
	9712	0x01f93000	0x02193000	      2048	rw-        	full          	guarded_heap_area
	9666	0x02204000	0x02304000	      1024	rw-        	full          	guarded_heap_area
	9716	0x0239c000	0x0259c000	      2048	rw-        	full          	guarded_heap_area
	9718	0x026d1000	0x028d1000	      2048	rw-        	full          	guarded_heap_area
	9717	0x0292f000	0x02b2f000	      2048	rw-        	full          	guarded_heap_area
	9715	0x02c51000	0x02e51000	      2048	rw-        	full          	guarded_heap_area
	9720	0x02e7e000	0x0307e000	      2048	rw-        	full          	guarded_heap_area
	9719	0x03119000	0x03319000	      2048	rw-        	full          	guarded_heap_area
	9721	0x03351000	0x03551000	      2048	rw-        	full          	guarded_heap_area
	9714	0x0356e000	0x0376e000	      2048	rw-        	full          	guarded_heap_area
	9713	0x03976000	0x03b76000	      2048	rw-        	full          	guarded_heap_area
	9665	0x045f5000	0x0460d000	        96	rw-        	full          	rld heap
	9664	0x06277000	0x0628f000	        96	rw-        	full          	rld heap
	9663	0x06874000	0x06884000	        64	rw-        	full          	rld heap
	9662	0x07dc6000	0x07dd6000	        64	rw-        	full          	rld heap
	9661	0x0af5e000	0x0af66000	        32	rw-        	full          	rld heap
	9678	0x60000000	0x60001000	         4	rw-S       	full          	server_memory
	9680	0x68000000	0x68036000	       216	rw-S       	full          	server_memory
	9683	0x70000000	0x70020000	       128	rw-S       	full          	server_memory
	9685	0x78000000	0x78058000	       352	rw-S       	full          	server_memory
	9687	0x80000000	0x80058000	       352	rw-S       	full          	server_memory
	9690	0x88000000	0x88058000	       352	rw-S       	full          	server_memory
	9692	0x90000000	0x90025000	       148	rw-S       	full          	server_memory
	9695	0x98000000	0x98129000	      1188	rw-S       	full          	server_memory
	9699	0xa0000000	0xa1339000	     19684	rw-S       	full          	server_memory
	9660	0x19c9414000	0x19c941c000	        32	rw-        	full          	rld heap
	9650	0x1c033b3000	0x1c033f4000	       260	r-x        	full          	libnetwork.so_seg0ro
	9651	0x1c035f3000	0x1c035f6000	        12	rw-        	full          	libnetwork.so_seg1rw
	9652	0x1c035f6000	0x1c035fc000	        24	rw-        	full          	libnetwork.so_seg2rw
	9648	0x2e41511000	0x2e4160c000	      1004	r-x        	full          	libtextencoding.so_seg0ro
	9649	0x2e4180c000	0x2e4180f000	        12	rw-        	full          	libtextencoding.so_seg1rw
	9607	0x2f76a4e000	0x2f76a4f000	         4	rw-S       	full          	_rld_debug_
	9653	0x5855a33000	0x5855c35000	      2056	r-x        	full          	libcrypto.so.1.0.0_seg0ro
	9654	0x5855e34000	0x5855e5b000	       156	rw-        	full          	libcrypto.so.1.0.0_seg1rw
	9655	0x5855e5b000	0x5855e5d000	         8	rw-        	full          	libcrypto.so.1.0.0_seg2rw
	9606	0x5e1e006000	0x5e1e016000	        64	rw-        	full          	rld heap
	9624	0x88e37a5000	0x88e38fb000	      1368	r-x        	full          	libxml2.so.2.9.9_seg0ro
	9625	0x88e3afb000	0x88e3b06000	        44	rw-        	full          	libxml2.so.2.9.9_seg1rw
	9626	0x88e3b06000	0x88e3b08000	         8	rw-        	full          	libxml2.so.2.9.9_seg2rw
	9618	0x9214033000	0x9214048000	        84	r-x        	full          	libtranslation.so_seg0ro
	9619	0x9214247000	0x9214249000	         8	rw-        	full          	libtranslation.so_seg1rw
	9603	0x99501af000	0x99501d0000	       132	r-x        	full          	runtime_loader_seg0ro
	9604	0x99503cf000	0x99503d1000	         8	rw-        	full          	runtime_loader_seg1rw
	9605	0x99503d1000	0x99503d2000	         4	rw-        	full          	runtime_loader_bss1
	9656	0xc112025000	0xc11208f000	       424	r-x        	full          	libssl.so.1.0.0_seg0ro
	9657	0xc11228e000	0xc112299000	        44	rw-        	full          	libssl.so.1.0.0_seg1rw
	9620	0xcfea1cd000	0xcfea233000	       408	r-x        	full          	libbnetapi.so_seg0ro
	9621	0xcfea433000	0xcfea438000	        20	rw-        	full          	libbnetapi.so_seg1rw
	9646	0x10fad6db000	0x10fad7ae000	       844	r-x        	full          	libzstd.so.1.3.8_seg0ro
	9647	0x10fad9ae000	0x10fad9af000	         4	rw-        	full          	libzstd.so.1.3.8_seg1rw
	9642	0x1289d86b000	0x1289da03000	      1632	r-x        	full          	libicuuc.so.57.1_seg0ro
	9643	0x1289dc02000	0x1289dc17000	        84	rw-        	full          	libicuuc.so.57.1_seg1rw
	9627	0x1326f916000	0x1326f92c000	        88	r-x        	full          	libgcc_s.so.1_seg0ro
	9628	0x1326fb2b000	0x1326fb2c000	         4	rw-        	full          	libgcc_s.so.1_seg1rw
	9635	0x13cff865000	0x13cff8ba000	       340	r-x        	full          	libicule.so.57.1_seg0ro
	9636	0x13cffaba000	0x13cffabd000	        12	rw-        	full          	libicule.so.57.1_seg1rw
	9613	0x150d865d000	0x150d87bf000	      1416	r-x        	full          	libstdc++.so.6.0.25_seg0ro
	9614	0x150d89bf000	0x150d89cb000	        48	rw-        	full          	libstdc++.so.6.0.25_seg1rw
	9615	0x150d89cb000	0x150d89d3000	        32	rw-        	full          	libstdc++.so.6.0.25_seg2rw
	9658	0x195912e6000	0x195912ed000	        28	r-x        	full          	libbsd.so_seg0ro
	9659	0x195914ec000	0x195914ed000	         4	rw-        	full          	libbsd.so_seg1rw
	9633	0x1bb20207000	0x1bb20213000	        48	r-x        	full          	libicuio.so.57.1_seg0ro
	9634	0x1bb20412000	0x1bb20414000	         8	rw-        	full          	libicuio.so.57.1_seg1rw
	9622	0x1caab076000	0x1caab12a000	       720	r-x        	full          	libmedia.so_seg0ro
	9623	0x1caab32a000	0x1caab336000	        48	rw-        	full          	libmedia.so_seg1rw
	9637	0x1d408c1c000	0x1d408c27000	        44	r-x        	full          	libiculx.so.57.1_seg0ro
	9638	0x1d408e27000	0x1d408e28000	         4	rw-        	full          	libiculx.so.57.1_seg1rw
	9608	0x1d8ba1da000	0x1d8ba207000	       180	r-x        	full          	StreamRadio_seg0ro
	9609	0x1d8ba407000	0x1d8ba40a000	        12	rw-        	full          	StreamRadio_seg1rw
	9644	0x1e22b225000	0x1e22b241000	       112	r-x        	full          	libz.so.1.2.11_seg0ro
	9645	0x1e22b440000	0x1e22b441000	         4	rw-        	full          	libz.so.1.2.11_seg1rw
	9639	0x1e25ffe4000	0x1e260013000	       188	r-x        	full          	libicutu.so.57.1_seg0ro
	9640	0x1e260213000	0x1e260215000	         8	rw-        	full          	libicutu.so.57.1_seg1rw
	9641	0x1e260215000	0x1e260247000	       200	rw-        	full          	libicutu.so.57.1_seg2rw
	9631	0x1e29bd21000	0x1e29bf9e000	      2548	r-x        	full          	libicui18n.so.57.1_seg0ro
	9632	0x1e29c19d000	0x1e29c1b2000	        84	rw-        	full          	libicui18n.so.57.1_seg1rw
	9616	0x1fa10dba000	0x1fa110d2000	      3168	r-x        	full          	libbe.so_seg0ro
	9617	0x1fa112d2000	0x1fa11300000	       184	rw-        	full          	libbe.so_seg1rw
	9629	0x2081082d000	0x208120ab000	     25080	r-x        	full          	libicudata.so.57.1_seg0ro
	9630	0x208122aa000	0x208122ab000	         4	rw-        	full          	libicudata.so.57.1_seg1rw
	9610	0x2095f368000	0x2095f4c9000	      1412	r-x        	full          	libroot_debug.so_seg0ro
	9611	0x2095f6c9000	0x2095f6d7000	        56	rw-        	full          	libroot_debug.so_seg1rw
	9612	0x2095f6d7000	0x2095f71b000	       272	rw-        	full          	libroot_debug.so_seg2rw
	9600	0x7fbc008dd000	0x7fbc008e1000	        16	rw-        	full          	user area
	9601	0x7feee6ff7000	0x7feee7ffd000	     16408	rw-s       	full          	StreamRadio_920_stack
	9602	0x7fff3d81d000	0x7fff3d825000	        32	r-xS       	full          	commpage

Protection Flags: r - read, w - write, x - execute, s - stack, o - overcommit, c - cloneable, S - shared, k - kernel

Semaphores:
	ID		Count	Last Holder	Name
	------------------------------------------------------------
	4732	    0	          0	some BBlockCache lock
	4733	    0	          0	token space
	4734	    0	          0	BLooperList lock
	4735	    0	          0	AppServerLink_sLock
	4736	    0	          0	some BLocker
	4737	    0	          0	some BLocker
	4738	    0	          0	Catalog
	4739	    0	          0	LocaleRosterData
	4740	    0	          0	some BLocker
	4741	    0	          0	Catalog
	4742	    0	          0	DNS cache
	4743	    0	          0	synchronized hash map
	4744	    0	          0	synchronized hash map
	4745	    0	          0	some BLocker
	4746	    0	          0	some BLocker
	4747	    0	          0	BMediaRoster::Roster locker
	4748	    0	          0	media theme lock
	4749	    0	          0	add-on manager
	4750	    0	          0	port pool
	4751	    0	          0	shared buffer list
	4752	    0	          0	media plugin manager
	4753	    0	          0	BMessageQueue Lock
	4754	    0	          0	AppLooperPort
	4766	    0	          0	screen list
	4767	    0	          0	clipboard
	4768	    0	          0	width buffer
``

**Comment by diversys** [comment]
I'just built 26f3bbda29da165c849d246038af98e17270249c and it crashes with the same back trace.

**Comment by diversys** [comment]
Also built current version at haikuports (after commenting out PATCHES) and it has the same problem.

**Comment by jsteinaker** [comment]
Thank you all for the feedback.

I ran StreamRadio using malloc_debug=g. It did not crash on startup. BUT, it crashed when doing a search, so I've just fixed that on my repo.

However, if you double-click on an empty space on the stations list on the main window, it crashes (with or without malloc_debug=g). It might be related to https://github.com/fishpond-haiku/Haiku-Radio/issues/4 and I guess it might be related to the crash you're experiencing as well.

I'll keep further investigating this.

**Comment by diversys** [comment]
Still crashes with your fix applied.

**Comment by diversys** [comment]
MALLOC_DEBUG=g StreamRadio

![image](https://user-images.githubusercontent.com/1316513/61074616-c9057e80-a420-11e9-8d43-13397ac3e3fd.png)

**Comment by jsteinaker** [comment]
Well, that was... ¿expected? The crash I fixed was apparently a different one.

I've just fixed the one happening when double-clicking the main window. Not that should fix the crash you're experiencing on startup, since I can't reproduce that one, even with MALLOC_DEBUG=g (and MALLOC_DEBUG it's working, cause I wasn't seeing the crashes I've just fixed before enabling the flag). I'll keep looking around the code in your screenshot.

Again, thanks for the feedback, it's much appreciated.

**Comment by jsteinaker** [comment]
A couple of lines before the line marked in your screenshot, when casting to (BGroupLayout*), there's a space that shouldn't be there between BGroupLayout and the * character... could be this? I've tried it and it compiles and works OK, but I wasn't experiencing the crash in first place so I can't tell...

**Comment by diversys** [comment]
With your new fix and with space removed it still crashes as before. In release mode as in description and in debug mode in MainWindow.cpp. Have you tried `make clean` and rebuilding again?

**Comment by Vidrep** [comment]
How about a real time discussion on IRC at #haiku-3rdparty

**Comment by jsteinaker** [comment]
Just did it, same result, works fine here (I even started with a fresh virtual machine and different hrev at some point)

@Vidrep I'm leaving now, but I'm up for that at a different moment.

**Comment by diversys** [comment]
What gcc do you have? Note, that by default it is still gcc7 now.

**Comment by waddlesplash** [comment]
Huh? No, we are using GCC8?

**Comment by diversys** [comment]
anyboot images still have gcc7 by default I believe.

**Comment by jsteinaker** [comment]
Will check later, but definitely whatever is on latest x64 nightly anyboot by default

**Comment by jsteinaker** [comment]
gcc 7.3.0 here

**Comment by diversys** [comment]
So, can you try with gcc8?

**Comment by jsteinaker** [comment]
Updated to gcc-8.3.0, make clean, recompiled. Aaaaaand we have a crash on startup, finally.
Also, A LOT more warnings during compilation (it was only throwing a small one with gcc7).

I guess I should start reading them, but that's a different story. Any pointers in the right direction are very welcome. If anyone wants to try the changes in StreamRadio in the meantime, gcc7 is the answer.

**Comment by jsteinaker** [comment]
Ok, the warnings and runtime errors were related and fortunately the fixes were easy. Can you please try them? I've already made a pull request, I'll make another for the haikuports tree as soon as this one is approved.

**Comment by diversys** [comment]
Thanks! It release version doesn't crash anymore in 9d387c7de01c1e0a33d09b3848fdcf290e7878c9.
However, it still crashes when compiled with `DEBUGGER := TRUE`.

**Comment by jsteinaker** [comment]
Great. I'll keep investigating the matter. Should we close this? (Or maybe change the subject to reflect the crash was about the transition to gcc8, and not about the changes made). Thanks!

**Comment by Vidrep** [comment]
StreamRadio now launching without a crash when built with gcc8.3. Closing as fixed. Thank you for looking into this issue!
